# Generated by Django 3.1 on 2020-09-09 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Spl',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('labeler', models.CharField(max_length=200)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spls', to='dailymed.set')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('spl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='dailymed.spl')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='dailymed.product')),
            ],
        ),
    ]
