version: '3.7'

services:

  api:
    build:
      context: .
    container_name: dailymed-api
    command: >
      sh -c 'python ./api/manage.py migrate &&\
             python ./api/manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - ./:/dailymed-api
      - ./data:/dailymed-api/data
