name: Tests

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7.9, 3.8]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup
      run: pip install poetry

    - name: Create venv
      uses: gabrielfalcao/pyenv-action@v5
      with:
        default: ${{ matrix.python }}
  
    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry install

    - name: Styling
      run: |
        flake8

    - name: Test
      run: |
        python3 api/manage.py test api/