name: Django CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      run: |
        pip install -U pip
        pip install poetry
        poetry install
        echo "/home/runner/work/dailymed-api/dailymed-api" >> $GITHUB_PATH
    - name: Run Tests
      working-directory: ./api
      run: |
        python manage.py test