name: DailyMed Tests

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup
      run: |
        pip install poetry
        poetry install
    - name: Run Tests
      working-directory: ./api
      run: |
        echo "/home/runner/work/dailymed-api" >> $GITHUB_PATH
        echo "::add-path::/home/runner/work/dailymed-api/"
        echo "::set-env name=PYTHONPATH::home/runner/work/dailymed-api"
        python3 manage.py test